const SHOP_DATA = [
  {
    id: 1,
    title: 'Liquorbrand Classic Flash Round Bag',
    description: ' Liquorbrand Classic Flash Tattoo Round Bag! This stunning vegan leather bag features an all-over tattoo print of moths, swallows, roses, anchors, black panthers and nautical stars on a neutral background. ',
    imageUrl: 'https://i.ibb.co/S6qwjSH/liquorbrand-classic-flash-tattoo-bag-81456-1599973053.jpg',
    price: 59,
  },
  {
    id: 2,
    title: 'Liquorbrand Gypsy Moth Bowler Bag',
    description: 'Liquorbrand Gypsy Moth Bowler Bag! This sleek bowler bag features an original and alternative print inspired by old school tattoo graphics - a Gypsy Moth. The print is repeated on both sides.',
    imageUrl: 'https://i.ibb.co/tqQMRjW/liquorbrand-gypsy-moth-bowler-bag-85390-1604715578.jpg',
    price: 59,
  },
  {
    id: 3,
    title: 'Liquorbrand Ouija Board Round Bag',
    description: "Liquorbrand Ouija Bag! You will be conjuring up spirits in no time with this stunner of a handbag. This medium size round bag features an ouija board print on both sides, has a rectangular base with 4 metal feet, twin grab handles and an adjustable and detachable shoulder strap. Fully lined (plain black) with internal zip pocket. It's the perfect alternative bag to keep all your pretties... and spirits insides.",
    imageUrl: 'https://i.ibb.co/mTdJy1G/ouija-bag-69381-1610624612.jpg',
    price: 69,
  },
  {
    id: 4,
    title: 'Liquorbrand Horror Bowler Bag',
    description: "Liquorbrand Horror Bowler Bag! One minute your entwined with your lover, the next you're faced with a monster! This spacious bowler bag features original artwork inspired by old school horror movies - a pin up beauty with explicit tattoos in the grasp of her undead lover. Print repeated on both sides.",
    imageUrl: 'https://i.ibb.co/WPytR1D/liquorbrand-horror-bowler-bag-67535-1599973735.jpg',
    price: 69,
  },
  {
    id: 5,
    title: 'Liquorbrand Stewed Screwed Tattooed Bowler Bag',
    description: " Liquorbrand Stewed Screwed and Tattooed Bowler Bag! For the rockabilly girl, this bowler will steal your heart. On both sides it features a full colour graphic of a tattooed rockabilly pin up, stewing in a glass of liquor! It's a small bowler bag yet easily fits the essentials. Print is repeated on both sides.",
    imageUrl: 'https://i.ibb.co/xHXydCL/stewed-screwed-tattooed-bowler-37848-1522544842.webp',
    price: 49,
  },
  {
    id: 6,
    title: 'Liquorbrand Flamingos Round Bag',
    description: 'The Mini Circle is the ultimate multipurpose grab and go style. Transfer it from crossbody to waistbelt to wristlet simply by changing straps. Internal built-in battery that can charge your USB device. Vegan friendly.',
    imageUrl: 'https://i.ibb.co/CJ1TL27/flamingo-bag-52014-1581590432.jpg',
    price: 69,
  },
  {
    id: 7,
    title: 'Six Bunnies Paradise Nappy Bag or Tote Bag',
    description: 'Liquorbrand Vega Mint Bowler Bag! All that glitters is gold and this Mint Green is sublime. This classic bowler bag has a matte black "tuck n roll" upholstery look with glossy mint glitter panel. It features Liquorbrand Chevron V hardware. Long grab handles can be worn over the shoulder.',
    imageUrl: 'https://i.ibb.co/jhjYsCx/six-bunnies-paradise-nappy-tote-bag-08978-1580526156.webp',
    price: 79,
  },
  {
    id: 8,
    title: 'Liquorbrand Dark Seas Bowler Bag',
    description: 'Liquorbrand Dark Seas Bowler Bag is a fine sight for any sailors eyes! This spacious bowler bag features original tattoo artwork - a sugar skull gypsy sailor framed by a cameo of roses, swallows and text, "Dark Seas." Print repeated on both sides. ',
    imageUrl: 'https://i.ibb.co/yRzmQ57/liquorbrand-dark-sea-bowler-bag-39737-1613193321.jpg',
    price: 59,
  },
  {
    id: 9,
    title: 'Liquorbrand Chevron Bowler Bag - Black',
    description: 'Combine your love of 1960s retro flavour and modern functionality with this stunning bowler bag! Inspired by the classic, metal flaked cars the outer upholstery is a high gloss in black with quilted pleating. Complete with Chevron badge. The tops and sides are a smooth faux leather. Long shoulder handles. The interior is specious to fit all the essentials and then some more. It has interior zipped pocket and twin side pockets. The rectangular base has protective metal feet.',
    imageUrl: 'https://i.ibb.co/55F3SMd/liquorbrand-black-chevron-bowler-bag-54897-1576220026.webp',
    price: 69,
  },
  {
    id: 10,
    title: 'Liquorbrand Leopard Plush Round Bag',
    description: 'A black round handbag with a feature soft leopard print on the base whilst the top is made from quality faux quilter leather. You have the choice of using the grab handles or a detachable shoulder strap, making this bag versatile! The base has four metal feet, the interior is lined, has two organiser pockets and a zipper pocket. Rockabilly and pin up queens, grab this bag and make it your staple statement piece.',
    imageUrl: 'https://i.ibb.co/cxGDtd2/liquorbrand-leopard-print-round-bag-53608-1584775130.webp',
    price: 69,
  },
  {
    id: 11,
    title: 'Liquorbrand Eternal Bliss Bowler Bag',
    description: 'An alternative and Gothic print of a Day of the Dead inspired, sugar skull gypsy praying the rosary over a skull. This is printed on soft satin-like fabric. The top and sides are made of faux leather, the inside is lined and the base has four metal feet. This is a high quality, must-have bag to add to any alternative and Gothic inspired accessory collection.',
    imageUrl: 'https://i.ibb.co/x5Gn7d0/eternal-bliss-bowler-06178-1602318663.jpg',
    price: 59,
  },
  {
    id: 12,
    title: 'Liquorbrand Hula Girl Bowler Bag',
    description: 'Instantly transport yourself to a tropical locale with this printed Hula Girl purse in blue from Liquorbrand! With an all over pattern of ukulele playing pinup girls and tropical flowers, It features embossed zipper pullers, metal feet, and their signature metal embossed logo plate. Functional side pockets keep your essentials within reach. The shoulder strap is adjustable and removable if you wish to take it from handbag to crossbody style for hands free ease.',
    imageUrl: 'https://i.ibb.co/MZ47N61/5889.jpg',
    price: 59,
  },
  {
    id: 13,
    title: 'Liquorbrand Tequila Bowler Bag',
    description: 'Liquorbrand Tequila Bowler Bag! This spacious bowler bag features original artwork in monochrome colour with red highlights - a day of the dead gypsy embracing the grim reaper. Print repeated on both sides.',
    imageUrl: 'https://i.ibb.co/7yq5fd8/6588.jpg',
    price: 69,
  },
  {
    id: 14,
    title: 'Liquorbrand La Vida Bowler Bag',
    description: "Liquor Brand LA VIDA Classic Bowler Bag Purse NO VALE NADA Life it's worth nothing Dia De Los Muertos Day of the Dead Punk Rockabilly bottom middle and top of bag are faux leather satin like sides foam padding embossed zipper pulls metal feet large embossed liquor brand logo on sides printed on both sides brand new in package 11 inches wide 7.5 inches high.",
    imageUrl: 'https://i.ibb.co/LvdLHTZ/3749.jpg',
    price: 69,
  },
  {
    id: 15,
    title: 'Liquorbrand Death Flash Bowler Bag',
    description: "Reapers, kewpies, skulls and more adorn this gorgeous Death Flash bowler bag from Liquorbrand. This purse is made of faux leather and features quilted side panels with metal logos, foam padding, metal feet and embossed zipper pulls. It's a nice, generous size and will easily fit all of your essentials!",
    imageUrl: 'https://i.ibb.co/wBvtYgh/6590.jpg',
    price: 59,
  },
];

export default SHOP_DATA;